# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Asterisk-CDR
version:      0.01
version_from: lib/Asterisk/CDR.pm
installdirs:  site
requires:
    Class::DBI::Frozen::301:       

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
